### ISSUE TITLE
Separate xk6 library from xk6 and k6 binaries

### ISSUE THREAD

**Issue by andrewslotin** [grafana/xk6#92]
Organize the code of xk6 into two main repositories, one for the functionalities that could be used by multiple binaries (k6, xk6, build service) and the other for the xk6 command. This would facilitate the versioning of the library independently of the xk6 command versioning (which we expect to have more changes initially
```[tasklist]
### Tasks
- [ ] Create a skeleton library for xk6-lib
- [ ] Collect dependencies using the xk6-lib
- [ ] Dependency resolution
- [ ] Use xk6-lib and github.com/szkiba/k6x to build the binary
- [ ] https://github.com/grafana/xk6/issues/96
```

**Comment by pablochacin** [comment]
xk6 is beeing replaced by new set tools:
* [k6deps](github.com/grafana/k6deps)
* [k6foundry](github.com/grafana/k6foundry)
* [k6catalog](github.com/grafana/k6catalog)
* [k6build](github.com/grafana/k6biuld)
* [k6toolbox](github.com/grafana/k6ftb)
